/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import java.math.BigDecimal;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
//import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

import uk.co.twinn.api.woocommerce.core.JacksonObjectMapper;

/**
 * OrderTaxLine
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class OrderTaxLine {
  public static final String SERIALIZED_NAME_ID = "id";
  //@SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_RATE_CODE = "rate_code";
  //@SerializedName(SERIALIZED_NAME_RATE_CODE)
  @javax.annotation.Nullable
  private String rateCode;

  public static final String SERIALIZED_NAME_RATE_ID = "rate_id";
  //@SerializedName(SERIALIZED_NAME_RATE_ID)
  @javax.annotation.Nullable
  private String rateId;

  public static final String SERIALIZED_NAME_LABEL = "label";
  //@SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private String label;

  public static final String SERIALIZED_NAME_COMPOUND = "compound";
  //@SerializedName(SERIALIZED_NAME_COMPOUND)
  @javax.annotation.Nullable
  private Boolean compound;

  public static final String SERIALIZED_NAME_TAX_TOTAL = "tax_total";
  //@SerializedName(SERIALIZED_NAME_TAX_TOTAL)
  @javax.annotation.Nullable
  private BigDecimal taxTotal;

  public static final String SERIALIZED_NAME_SHIPPING_TAX_TOTAL = "shipping_tax_total";
  //@SerializedName(SERIALIZED_NAME_SHIPPING_TAX_TOTAL)
  @javax.annotation.Nullable
  private BigDecimal shippingTaxTotal;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  //@SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<MetaData> metaData = new ArrayList<>();

  public OrderTaxLine() {
  }

  public OrderTaxLine id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Item ID.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public OrderTaxLine rateCode(@javax.annotation.Nullable String rateCode) {
    this.rateCode = rateCode;
    return this;
  }

  /**
   * Tax rate code.
   * @return rateCode
   */
  @javax.annotation.Nullable
  public String getRateCode() {
    return rateCode;
  }

  @JsonProperty("rate_code")
  public void setRateCode(@javax.annotation.Nullable String rateCode) {
    this.rateCode = rateCode;
  }


  public OrderTaxLine rateId(@javax.annotation.Nullable String rateId) {
    this.rateId = rateId;
    return this;
  }

  /**
   * Tax rate ID.
   * @return rateId
   */
  @javax.annotation.Nullable
  public String getRateId() {
    return rateId;
  }

  @JsonProperty("rate_id")
  public void setRateId(@javax.annotation.Nullable String rateId) {
    this.rateId = rateId;
  }


  public OrderTaxLine label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * Tax rate label.
   * @return label
   */
  @javax.annotation.Nullable
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public OrderTaxLine compound(@javax.annotation.Nullable Boolean compound) {
    this.compound = compound;
    return this;
  }

  /**
   * Whether or not this is a compound tax rate.
   * @return compound
   */
  @javax.annotation.Nullable
  public Boolean getCompound() {
    return compound;
  }

  public void setCompound(@javax.annotation.Nullable Boolean compound) {
    this.compound = compound;
  }


  public OrderTaxLine taxTotal(@javax.annotation.Nullable BigDecimal taxTotal) {
    this.taxTotal = taxTotal;
    return this;
  }

  /**
   * Tax total (not including shipping taxes).
   * @return taxTotal
   */
  @javax.annotation.Nullable
  public BigDecimal getTaxTotal() {
    return taxTotal;
  }

  @JsonProperty("tax_total")
  public void setTaxTotal(@javax.annotation.Nullable BigDecimal taxTotal) {
    this.taxTotal = taxTotal;
  }


  public OrderTaxLine shippingTaxTotal(@javax.annotation.Nullable BigDecimal shippingTaxTotal) {
    this.shippingTaxTotal = shippingTaxTotal;
    return this;
  }

  /**
   * Shipping tax total.
   * @return shippingTaxTotal
   */
  @javax.annotation.Nullable
  public BigDecimal getShippingTaxTotal() {
    return shippingTaxTotal;
  }

  @JsonProperty("shipping_tax_total")
  public void setShippingTaxTotal(@javax.annotation.Nullable BigDecimal shippingTaxTotal) {
    this.shippingTaxTotal = shippingTaxTotal;
  }


  public OrderTaxLine metaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
    return this;
  }

  public OrderTaxLine addMetaDataItem(MetaData metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data properties.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<MetaData> getMetaData() {
    return metaData;
  }

  @JsonProperty("meta_data")
  public void setMetaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderTaxLine orderTaxLine = (OrderTaxLine) o;
    return Objects.equals(this.id, orderTaxLine.id) &&
        Objects.equals(this.rateCode, orderTaxLine.rateCode) &&
        Objects.equals(this.rateId, orderTaxLine.rateId) &&
        Objects.equals(this.label, orderTaxLine.label) &&
        Objects.equals(this.compound, orderTaxLine.compound) &&
        Objects.equals(this.taxTotal, orderTaxLine.taxTotal) &&
        Objects.equals(this.shippingTaxTotal, orderTaxLine.shippingTaxTotal) &&
        Objects.equals(this.metaData, orderTaxLine.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, rateCode, rateId, label, compound, taxTotal, shippingTaxTotal, metaData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderTaxLine {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rateCode: ").append(toIndentedString(rateCode)).append("\n");
    sb.append("    rateId: ").append(toIndentedString(rateId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    compound: ").append(toIndentedString(compound)).append("\n");
    sb.append("    taxTotal: ").append(toIndentedString(taxTotal)).append("\n");
    sb.append("    shippingTaxTotal: ").append(toIndentedString(shippingTaxTotal)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert an instance of OrderTaxLine to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
      return new JacksonObjectMapper().toJson(this);
  }
}

