/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import uk.co.twinn.api.woocommerce.core.JacksonObjectMapper;

/**
 * OrderLineItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class OrderLineItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PARENT_NAME = "parent_name";
  @SerializedName(SERIALIZED_NAME_PARENT_NAME)
  @javax.annotation.Nullable
  private String parentName;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nullable
  private Integer productId;

  public static final String SERIALIZED_NAME_VARIATION_ID = "variation_id";
  @SerializedName(SERIALIZED_NAME_VARIATION_ID)
  @javax.annotation.Nullable
  private Integer variationId;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  @javax.annotation.Nullable
  private Integer quantity;

  public static final String SERIALIZED_NAME_TAX_CLASS = "tax_class";
  @SerializedName(SERIALIZED_NAME_TAX_CLASS)
  @javax.annotation.Nullable
  private String taxClass;

  public static final String SERIALIZED_NAME_SUBTOTAL = "subtotal";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL)
  @javax.annotation.Nullable
  private BigDecimal subtotal;

  public static final String SERIALIZED_NAME_SUBTOTAL_TAX = "subtotal_tax";
  @SerializedName(SERIALIZED_NAME_SUBTOTAL_TAX)
  @javax.annotation.Nullable
  private BigDecimal subtotalTax;

  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  @javax.annotation.Nullable
  private BigDecimal total;

  public static final String SERIALIZED_NAME_TOTAL_TAX = "total_tax";
  @SerializedName(SERIALIZED_NAME_TOTAL_TAX)
  @javax.annotation.Nullable
  private BigDecimal totalTax;

  public static final String SERIALIZED_NAME_TAXES = "taxes";
  @SerializedName(SERIALIZED_NAME_TAXES)
  @javax.annotation.Nullable
  private List<OrderTaxLine> taxes = new ArrayList<>();

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<MetaData> metaData = new ArrayList<>();

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nullable
  private String sku;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private BigDecimal price;

  public OrderLineItem() {
  }

  public OrderLineItem id(@javax.annotation.Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Item ID.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }


  public OrderLineItem name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Product name.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public OrderLineItem parentName(@javax.annotation.Nullable String parentName) {
    this.parentName = parentName;
    return this;
  }

  /**
   * Parent product name if the product is a variation.
   * @return parentName
   */
  @javax.annotation.Nullable
  public String getParentName() {
    return parentName;
  }

  @JsonProperty("parent_name")
  public void setParentName(@javax.annotation.Nullable String parentName) {
    this.parentName = parentName;
  }


  public OrderLineItem productId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Product ID.
   * @return productId
   */
  @javax.annotation.Nullable
  public Integer getProductId() {
    return productId;
  }

  @JsonProperty("product_id")
  public void setProductId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
  }


  public OrderLineItem variationId(@javax.annotation.Nullable Integer variationId) {
    this.variationId = variationId;
    return this;
  }

  /**
   * Variation ID, if applicable.
   * @return variationId
   */
  @javax.annotation.Nullable
  public Integer getVariationId() {
    return variationId;
  }

  @JsonProperty("variation_id")
  public void setVariationId(@javax.annotation.Nullable Integer variationId) {
    this.variationId = variationId;
  }


  public OrderLineItem quantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
    return this;
  }

  /**
   * Quantity ordered.
   * @return quantity
   */
  @javax.annotation.Nullable
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(@javax.annotation.Nullable Integer quantity) {
    this.quantity = quantity;
  }


  public OrderLineItem taxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
    return this;
  }

  /**
   * Tax class of product.
   * @return taxClass
   */
  @javax.annotation.Nullable
  public String getTaxClass() {
    return taxClass;
  }

  @JsonProperty("tax_class")
  public void setTaxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
  }


  public OrderLineItem subtotal(@javax.annotation.Nullable BigDecimal subtotal) {
    this.subtotal = subtotal;
    return this;
  }

  /**
   * Line subtotal (before discounts).
   * @return subtotal
   */
  @javax.annotation.Nullable
  public BigDecimal getSubtotal() {
    return subtotal;
  }

  public void setSubtotal(@javax.annotation.Nullable BigDecimal subtotal) {
    this.subtotal = subtotal;
  }


  public OrderLineItem subtotalTax(@javax.annotation.Nullable BigDecimal subtotalTax) {
    this.subtotalTax = subtotalTax;
    return this;
  }

  /**
   * Line subtotal tax (before discounts).
   * @return subtotalTax
   */
  @javax.annotation.Nullable
  public BigDecimal getSubtotalTax() {
    return subtotalTax;
  }

  @JsonProperty("subtotal_tax")
  public void setSubtotalTax(@javax.annotation.Nullable BigDecimal subtotalTax) {
    this.subtotalTax = subtotalTax;
  }


  public OrderLineItem total(@javax.annotation.Nullable BigDecimal total) {
    this.total = total;
    return this;
  }

  /**
   * Line total (after discounts).
   * @return total
   */
  @javax.annotation.Nullable
  public BigDecimal getTotal() {
    return total;
  }

  public void setTotal(@javax.annotation.Nullable BigDecimal total) {
    this.total = total;
  }


  public OrderLineItem totalTax(@javax.annotation.Nullable BigDecimal totalTax) {
    this.totalTax = totalTax;
    return this;
  }

  /**
   * Line total tax (after discounts).
   * @return totalTax
   */
  @javax.annotation.Nullable
  public BigDecimal getTotalTax() {
    return totalTax;
  }

  @JsonProperty("total_tax")
  public void setTotalTax(@javax.annotation.Nullable BigDecimal totalTax) {
    this.totalTax = totalTax;
  }


  public OrderLineItem taxes(@javax.annotation.Nullable List<OrderTaxLine> taxes) {
    this.taxes = taxes;
    return this;
  }

  public OrderLineItem addTaxesItem(OrderTaxLine taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

  /**
   * Line taxes.
   * @return taxes
   */
  @javax.annotation.Nullable
  public List<OrderTaxLine> getTaxes() {
    return taxes;
  }

  public void setTaxes(@javax.annotation.Nullable List<OrderTaxLine> taxes) {
    this.taxes = taxes;
  }


  public OrderLineItem metaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
    return this;
  }

  public OrderLineItem addMetaDataItem(MetaData metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data properties.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<MetaData> getMetaData() {
    return metaData;
  }

  @JsonProperty("meta_data")
  public void setMetaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
  }


  public OrderLineItem sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * Product SKU.
   * @return sku
   */
  @javax.annotation.Nullable
  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public OrderLineItem price(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
    return this;
  }

  /**
   * Product price.
   * @return price
   */
  @javax.annotation.Nullable
  public BigDecimal getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable BigDecimal price) {
    this.price = price;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderLineItem orderLineItem = (OrderLineItem) o;
    return Objects.equals(this.id, orderLineItem.id) &&
        Objects.equals(this.name, orderLineItem.name) &&
        Objects.equals(this.parentName, orderLineItem.parentName) &&
        Objects.equals(this.productId, orderLineItem.productId) &&
        Objects.equals(this.variationId, orderLineItem.variationId) &&
        Objects.equals(this.quantity, orderLineItem.quantity) &&
        Objects.equals(this.taxClass, orderLineItem.taxClass) &&
        Objects.equals(this.subtotal, orderLineItem.subtotal) &&
        Objects.equals(this.subtotalTax, orderLineItem.subtotalTax) &&
        Objects.equals(this.total, orderLineItem.total) &&
        Objects.equals(this.totalTax, orderLineItem.totalTax) &&
        Objects.equals(this.taxes, orderLineItem.taxes) &&
        Objects.equals(this.metaData, orderLineItem.metaData) &&
        Objects.equals(this.sku, orderLineItem.sku) &&
        Objects.equals(this.price, orderLineItem.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, parentName, productId, variationId, quantity, taxClass, subtotal, subtotalTax, total, totalTax, taxes, metaData, sku, price);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderLineItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parentName: ").append(toIndentedString(parentName)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    variationId: ").append(toIndentedString(variationId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    subtotal: ").append(toIndentedString(subtotal)).append("\n");
    sb.append("    subtotalTax: ").append(toIndentedString(subtotalTax)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    totalTax: ").append(toIndentedString(totalTax)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert an instance of OrderLineItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
      return new JacksonObjectMapper().toJson(this);
  }

}

