/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import java.math.BigDecimal;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import uk.co.twinn.pl_wtx_woocommerce.invoker.JSON;

/**
 * ProductVariation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ProductVariation {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer variationId;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  @javax.annotation.Nullable
  private LocalDateTime dateCreated;

  public static final String SERIALIZED_NAME_DATE_CREATED_GMT = "date_created_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED_GMT)
  @javax.annotation.Nullable
  private LocalDateTime dateCreatedGmt;

  public static final String SERIALIZED_NAME_DATE_MODIFIED = "date_modified";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED)
  @javax.annotation.Nullable
  private LocalDateTime dateModified;

  public static final String SERIALIZED_NAME_DATE_MODIFIED_GMT = "date_modified_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_MODIFIED_GMT)
  @javax.annotation.Nullable
  private LocalDateTime dateModifiedGmt;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_PERMALINK = "permalink";
  @SerializedName(SERIALIZED_NAME_PERMALINK)
  @javax.annotation.Nullable
  private String permalink;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  @javax.annotation.Nullable
  private String sku;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private String price;

  public static final String SERIALIZED_NAME_REGULAR_PRICE = "regular_price";
  @SerializedName(SERIALIZED_NAME_REGULAR_PRICE)
  @javax.annotation.Nullable
  private String regularPrice;

  public static final String SERIALIZED_NAME_SALE_PRICE = "sale_price";
  @SerializedName(SERIALIZED_NAME_SALE_PRICE)
  @javax.annotation.Nullable
  private String salePrice;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_FROM = "date_on_sale_from";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_FROM)
  @javax.annotation.Nullable
  private LocalDateTime dateOnSaleFrom;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_FROM_GMT = "date_on_sale_from_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_FROM_GMT)
  @javax.annotation.Nullable
  private LocalDateTime dateOnSaleFromGmt;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_TO = "date_on_sale_to";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_TO)
  @javax.annotation.Nullable
  private LocalDateTime dateOnSaleTo;

  public static final String SERIALIZED_NAME_DATE_ON_SALE_TO_GMT = "date_on_sale_to_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_ON_SALE_TO_GMT)
  @javax.annotation.Nullable
  private LocalDateTime dateOnSaleToGmt;

  public static final String SERIALIZED_NAME_ON_SALE = "on_sale";
  @SerializedName(SERIALIZED_NAME_ON_SALE)
  @javax.annotation.Nullable
  private Boolean onSale;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_PURCHASABLE = "purchasable";
  @SerializedName(SERIALIZED_NAME_PURCHASABLE)
  @javax.annotation.Nullable
  private Boolean purchasable;

  public static final String SERIALIZED_NAME_VIRTUAL = "virtual";
  @SerializedName(SERIALIZED_NAME_VIRTUAL)
  @javax.annotation.Nullable
  private Boolean virtual;

  public static final String SERIALIZED_NAME_DOWNLOADABLE = "downloadable";
  @SerializedName(SERIALIZED_NAME_DOWNLOADABLE)
  @javax.annotation.Nullable
  private Boolean downloadable;

  public static final String SERIALIZED_NAME_DOWNLOADS = "downloads";
  @SerializedName(SERIALIZED_NAME_DOWNLOADS)
  @javax.annotation.Nullable
  private List<ProductDownload> downloads = new ArrayList<>();

  public static final String SERIALIZED_NAME_DOWNLOAD_LIMIT = "download_limit";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_LIMIT)
  @javax.annotation.Nullable
  private Integer downloadLimit;

  public static final String SERIALIZED_NAME_DOWNLOAD_EXPIRY = "download_expiry";
  @SerializedName(SERIALIZED_NAME_DOWNLOAD_EXPIRY)
  @javax.annotation.Nullable
  private Integer downloadExpiry;

  public static final String SERIALIZED_NAME_TAX_STATUS = "tax_status";
  @SerializedName(SERIALIZED_NAME_TAX_STATUS)
  @javax.annotation.Nullable
  private String taxStatus;

  public static final String SERIALIZED_NAME_TAX_CLASS = "tax_class";
  @SerializedName(SERIALIZED_NAME_TAX_CLASS)
  @javax.annotation.Nullable
  private String taxClass;

  public static final String SERIALIZED_NAME_MANAGE_STOCK = "manage_stock";
  @SerializedName(SERIALIZED_NAME_MANAGE_STOCK)
  @javax.annotation.Nullable
  private Boolean manageStock;

  public static final String SERIALIZED_NAME_STOCK_QUANTITY = "stock_quantity";
  @SerializedName(SERIALIZED_NAME_STOCK_QUANTITY)
  @javax.annotation.Nullable
  private Integer stockQuantity;

  public static final String SERIALIZED_NAME_STOCK_STATUS = "stock_status";
  @SerializedName(SERIALIZED_NAME_STOCK_STATUS)
  @javax.annotation.Nullable
  private String stockStatus;

  public static final String SERIALIZED_NAME_BACKORDERS = "backorders";
  @SerializedName(SERIALIZED_NAME_BACKORDERS)
  @javax.annotation.Nullable
  private String backorders;

  public static final String SERIALIZED_NAME_BACKORDERS_ALLOWED = "backorders_allowed";
  @SerializedName(SERIALIZED_NAME_BACKORDERS_ALLOWED)
  @javax.annotation.Nullable
  private Boolean backordersAllowed;

  public static final String SERIALIZED_NAME_BACKORDERED = "backordered";
  @SerializedName(SERIALIZED_NAME_BACKORDERED)
  @javax.annotation.Nullable
  private Boolean backordered;

  public static final String SERIALIZED_NAME_WEIGHT = "weight";
  @SerializedName(SERIALIZED_NAME_WEIGHT)
  @javax.annotation.Nullable
  private String weight;

  public static final String SERIALIZED_NAME_DIMENSIONS = "dimensions";
  @SerializedName(SERIALIZED_NAME_DIMENSIONS)
  @javax.annotation.Nullable
  private ProductDimension dimensions;

  public static final String SERIALIZED_NAME_SHIPPING_CLASS = "shipping_class";
  @SerializedName(SERIALIZED_NAME_SHIPPING_CLASS)
  @javax.annotation.Nullable
  private String shippingClass;

  public static final String SERIALIZED_NAME_SHIPPING_CLASS_ID = "shipping_class_id";
  @SerializedName(SERIALIZED_NAME_SHIPPING_CLASS_ID)
  @javax.annotation.Nullable
  private Integer shippingClassId;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  @javax.annotation.Nullable
  private ProductImage image;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  @javax.annotation.Nullable
  private List<ProductAttribute> attributes = new ArrayList<>();

  public static final String SERIALIZED_NAME_MENU_ORDER = "menu_order";
  @SerializedName(SERIALIZED_NAME_MENU_ORDER)
  @javax.annotation.Nullable
  private Integer menuOrder;

  public static final String SERIALIZED_NAME_META_DATA = "meta_data";
  @SerializedName(SERIALIZED_NAME_META_DATA)
  @javax.annotation.Nullable
  private List<MetaData> metaData = new ArrayList<>();

  public ProductVariation() {
  }

  public ProductVariation variationId(@javax.annotation.Nullable Integer variationId) {
    this.variationId = variationId;
    return this;
  }

  /**
   * Unique identifier for the resource. read-only
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty("id")
  public Integer getVariationId() {
    return variationId;
  }

  @JsonProperty("id")
  public void setVariationId(@javax.annotation.Nullable Integer variationId) {
    this.variationId = variationId;
  }

  public ProductVariation dateCreated(@javax.annotation.Nullable LocalDateTime dateCreated) {
    this.dateCreated = dateCreated;
    return this;
  }

  /**
   * The date the variation  was created, in the site&#39;s timezone. read-only
   * @return dateCreated
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateCreated() {
    return dateCreated;
  }

  public void setDateCreated(@javax.annotation.Nullable LocalDateTime dateCreated) {
    this.dateCreated = dateCreated;
  }


  public ProductVariation dateCreatedGmt(@javax.annotation.Nullable LocalDateTime dateCreatedGmt) {
    this.dateCreatedGmt = dateCreatedGmt;
    return this;
  }

  /**
   * The date the variation  was created, as GMT. read-only
   * @return dateCreatedGmt
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateCreatedGmt() {
    return dateCreatedGmt;
  }

  public void setDateCreatedGmt(@javax.annotation.Nullable LocalDateTime dateCreatedGmt) {
    this.dateCreatedGmt = dateCreatedGmt;
  }


  public ProductVariation dateModified(@javax.annotation.Nullable LocalDateTime dateModified) {
    this.dateModified = dateModified;
    return this;
  }

  /**
   * The date the variation  was last modified, in the site&#39;s timezone. read-only
   * @return dateModified
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateModified() {
    return dateModified;
  }

  public void setDateModified(@javax.annotation.Nullable LocalDateTime dateModified) {
    this.dateModified = dateModified;
  }


  public ProductVariation dateModifiedGmt(@javax.annotation.Nullable LocalDateTime dateModifiedGmt) {
    this.dateModifiedGmt = dateModifiedGmt;
    return this;
  }

  /**
   * The date the variation  was last modified, as GMT. read-only
   * @return dateModifiedGmt
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateModifiedGmt() {
    return dateModifiedGmt;
  }

  public void setDateModifiedGmt(@javax.annotation.Nullable LocalDateTime dateModifiedGmt) {
    this.dateModifiedGmt = dateModifiedGmt;
  }


  public ProductVariation description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Variation description.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public ProductVariation permalink(@javax.annotation.Nullable String permalink) {
    this.permalink = permalink;
    return this;
  }

  /**
   * Variation URL. read-only
   * @return permalink
   */
  @javax.annotation.Nullable
  public String getPermalink() {
    return permalink;
  }

  public void setPermalink(@javax.annotation.Nullable String permalink) {
    this.permalink = permalink;
  }


  public ProductVariation sku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
    return this;
  }

  /**
   * Unique identifier.
   * @return sku
   */
  @javax.annotation.Nullable
  public String getSku() {
    return sku;
  }

  public void setSku(@javax.annotation.Nullable String sku) {
    this.sku = sku;
  }


  public ProductVariation price(@javax.annotation.Nullable String price) {
    this.price = price;
    return this;
  }

  /**
   * Current variation price. read-only
   * @return price
   */
  @javax.annotation.Nullable
  public String getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable String price) {
    this.price = price;
  }


  public ProductVariation regularPrice(@javax.annotation.Nullable String regularPrice) {
    this.regularPrice = regularPrice;
    return this;
  }

  /**
   * Variation product price.
   * @return regularPrice
   */
  @javax.annotation.Nullable
  public String getRegularPrice() {
    return regularPrice;
  }

  public void setRegularPrice(@javax.annotation.Nullable String regularPrice) {
    this.regularPrice = regularPrice;
  }

public void setRegularPrice(@javax.annotation.Nullable BigDecimal regularPrice) {

    if (regularPrice != null) {
        setRegularPrice(regularPrice.toString());
    }

}

  public ProductVariation salePrice(@javax.annotation.Nullable String salePrice) {
    this.salePrice = salePrice;
    return this;
  }

  /**
   * Variation sale price.
   * @return salePrice
   */
  @javax.annotation.Nullable
  public String getSalePrice() {
    return salePrice;
  }

  public void setSalePrice(@javax.annotation.Nullable String salePrice) {
    this.salePrice = salePrice;
  }


 public void setSalePrice(@javax.annotation.Nullable BigDecimal salePrice) {

      if (salePrice != null) {
          setSalePrice(salePrice.toString());
      }

}


  public ProductVariation dateOnSaleFrom(@javax.annotation.Nullable LocalDateTime dateOnSaleFrom) {
    this.dateOnSaleFrom = dateOnSaleFrom;
    return this;
  }

  /**
   * Start date of sale price, in the site&#39;s timezone.
   * @return dateOnSaleFrom
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateOnSaleFrom() {
    return dateOnSaleFrom;
  }

  public void setDateOnSaleFrom(@javax.annotation.Nullable LocalDateTime dateOnSaleFrom) {
    this.dateOnSaleFrom = dateOnSaleFrom;
  }


  public ProductVariation dateOnSaleFromGmt(@javax.annotation.Nullable LocalDateTime dateOnSaleFromGmt) {
    this.dateOnSaleFromGmt = dateOnSaleFromGmt;
    return this;
  }

  /**
   * Start date of sale price, as GMT.
   * @return dateOnSaleFromGmt
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateOnSaleFromGmt() {
    return dateOnSaleFromGmt;
  }

  public void setDateOnSaleFromGmt(@javax.annotation.Nullable LocalDateTime dateOnSaleFromGmt) {
    this.dateOnSaleFromGmt = dateOnSaleFromGmt;
  }


  public ProductVariation dateOnSaleTo(@javax.annotation.Nullable LocalDateTime dateOnSaleTo) {
    this.dateOnSaleTo = dateOnSaleTo;
    return this;
  }

  /**
   * End date of sale price, in the site&#39;s timezone.
   * @return dateOnSaleTo
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateOnSaleTo() {
    return dateOnSaleTo;
  }

  public void setDateOnSaleTo(@javax.annotation.Nullable LocalDateTime dateOnSaleTo) {
    this.dateOnSaleTo = dateOnSaleTo;
  }


  public ProductVariation dateOnSaleToGmt(@javax.annotation.Nullable LocalDateTime dateOnSaleToGmt) {
    this.dateOnSaleToGmt = dateOnSaleToGmt;
    return this;
  }

  /**
   * End date of sale price, as GMT.
   * @return dateOnSaleToGmt
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateOnSaleToGmt() {
    return dateOnSaleToGmt;
  }

  public void setDateOnSaleToGmt(@javax.annotation.Nullable LocalDateTime dateOnSaleToGmt) {
    this.dateOnSaleToGmt = dateOnSaleToGmt;
  }


  public ProductVariation onSale(@javax.annotation.Nullable Boolean onSale) {
    this.onSale = onSale;
    return this;
  }

  /**
   * Shows if the variation is on sale. read-only
   * @return onSale
   */
  @javax.annotation.Nullable
  public Boolean getOnSale() {
    return onSale;
  }

  public void setOnSale(@javax.annotation.Nullable Boolean onSale) {
    this.onSale = onSale;
  }


  public ProductVariation status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Variation status. Options: draft, pending, private and publish. Default is publish.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  public ProductVariation purchasable(@javax.annotation.Nullable Boolean purchasable) {
    this.purchasable = purchasable;
    return this;
  }

  /**
   * Shows if the variation can be bought. read-only
   * @return purchasable
   */
  @javax.annotation.Nullable
  public Boolean getPurchasable() {
    return purchasable;
  }

  public void setPurchasable(@javax.annotation.Nullable Boolean purchasable) {
    this.purchasable = purchasable;
  }


  public ProductVariation virtual(@javax.annotation.Nullable Boolean virtual) {
    this.virtual = virtual;
    return this;
  }

  /**
   * If the variation is virtual. Default is false.
   * @return virtual
   */
  @javax.annotation.Nullable
  public Boolean getVirtual() {
    return virtual;
  }

  public void setVirtual(@javax.annotation.Nullable Boolean virtual) {
    this.virtual = virtual;
  }


  public ProductVariation downloadable(@javax.annotation.Nullable Boolean downloadable) {
    this.downloadable = downloadable;
    return this;
  }

  /**
   * If the variation is downloadable. Default is false.
   * @return downloadable
   */
  @javax.annotation.Nullable
  public Boolean getDownloadable() {
    return downloadable;
  }

  public void setDownloadable(@javax.annotation.Nullable Boolean downloadable) {
    this.downloadable = downloadable;
  }


  public ProductVariation downloads(@javax.annotation.Nullable List<ProductDownload> downloads) {
    this.downloads = downloads;
    return this;
  }

  public ProductVariation addDownloadsItem(ProductDownload downloadsItem) {
    if (this.downloads == null) {
      this.downloads = new ArrayList<>();
    }
    this.downloads.add(downloadsItem);
    return this;
  }

  /**
   * List of downloadable files.
   * @return downloads
   */
  @javax.annotation.Nullable
  public List<ProductDownload> getDownloads() {
    return downloads;
  }

  public void setDownloads(@javax.annotation.Nullable List<ProductDownload> downloads) {
    this.downloads = downloads;
  }


  public ProductVariation downloadLimit(@javax.annotation.Nullable Integer downloadLimit) {
    this.downloadLimit = downloadLimit;
    return this;
  }

  /**
   * Number of times downloadable files can be downloaded after purchase. Default is -1.
   * @return downloadLimit
   */
  @javax.annotation.Nullable
  public Integer getDownloadLimit() {
    return downloadLimit;
  }

  public void setDownloadLimit(@javax.annotation.Nullable Integer downloadLimit) {
    this.downloadLimit = downloadLimit;
  }


  public ProductVariation downloadExpiry(@javax.annotation.Nullable Integer downloadExpiry) {
    this.downloadExpiry = downloadExpiry;
    return this;
  }

  /**
   * Number of days until access to downloadable files expires. Default is -1.
   * @return downloadExpiry
   */
  @javax.annotation.Nullable
  public Integer getDownloadExpiry() {
    return downloadExpiry;
  }

  public void setDownloadExpiry(@javax.annotation.Nullable Integer downloadExpiry) {
    this.downloadExpiry = downloadExpiry;
  }


  public ProductVariation taxStatus(@javax.annotation.Nullable String taxStatus) {
    this.taxStatus = taxStatus;
    return this;
  }

  /**
   * Tax status. Options: taxable, shipping and none. Default is taxable.
   * @return taxStatus
   */
  @javax.annotation.Nullable
  public String getTaxStatus() {
    return taxStatus;
  }

  public void setTaxStatus(@javax.annotation.Nullable String taxStatus) {
    this.taxStatus = taxStatus;
  }


  public ProductVariation taxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
    return this;
  }

  /**
   * Tax class.
   * @return taxClass
   */
  @javax.annotation.Nullable
  public String getTaxClass() {
    return taxClass;
  }

  public void setTaxClass(@javax.annotation.Nullable String taxClass) {
    this.taxClass = taxClass;
  }


  public ProductVariation manageStock(@javax.annotation.Nullable Boolean manageStock) {
    this.manageStock = manageStock;
    return this;
  }

  /**
   * Stock management at variation level. Default is false.
   * @return manageStock
   */
  @javax.annotation.Nullable
  public Boolean getManageStock() {
    return manageStock;
  }

  public void setManageStock(@javax.annotation.Nullable Boolean manageStock) {
    this.manageStock = manageStock;
  }


  public ProductVariation stockQuantity(@javax.annotation.Nullable Integer stockQuantity) {
    this.stockQuantity = stockQuantity;
    return this;
  }

  /**
   * Stock quantity.
   * @return stockQuantity
   */
  @javax.annotation.Nullable
  public Integer getStockQuantity() {
    return stockQuantity;
  }

  public void setStockQuantity(@javax.annotation.Nullable Integer stockQuantity) {
    this.stockQuantity = stockQuantity;
  }


  public ProductVariation stockStatus(@javax.annotation.Nullable String stockStatus) {
    this.stockStatus = stockStatus;
    return this;
  }

  /**
   * Controls the stock status of the product. Options: instock, outofstock, onbackorder. Default is instock.
   * @return stockStatus
   */
  @javax.annotation.Nullable
  public String getStockStatus() {
    return stockStatus;
  }

  public void setStockStatus(@javax.annotation.Nullable String stockStatus) {
    this.stockStatus = stockStatus;
  }


  public ProductVariation backorders(@javax.annotation.Nullable String backorders) {
    this.backorders = backorders;
    return this;
  }

  /**
   * If managing stock, this controls if backorders are allowed. Options: no, notify and yes. Default is no.
   * @return backorders
   */
  @javax.annotation.Nullable
  public String getBackorders() {
    return backorders;
  }

  public void setBackorders(@javax.annotation.Nullable String backorders) {
    this.backorders = backorders;
  }


  public ProductVariation backordersAllowed(@javax.annotation.Nullable Boolean backordersAllowed) {
    this.backordersAllowed = backordersAllowed;
    return this;
  }

  /**
   * Shows if backorders are allowed. read-only
   * @return backordersAllowed
   */
  @javax.annotation.Nullable
  public Boolean getBackordersAllowed() {
    return backordersAllowed;
  }

  public void setBackordersAllowed(@javax.annotation.Nullable Boolean backordersAllowed) {
    this.backordersAllowed = backordersAllowed;
  }


  public ProductVariation backordered(@javax.annotation.Nullable Boolean backordered) {
    this.backordered = backordered;
    return this;
  }

  /**
   * Shows if the variation is on backordered. read-only
   * @return backordered
   */
  @javax.annotation.Nullable
  public Boolean getBackordered() {
    return backordered;
  }

  public void setBackordered(@javax.annotation.Nullable Boolean backordered) {
    this.backordered = backordered;
  }


  public ProductVariation weight(@javax.annotation.Nullable String weight) {
    this.weight = weight;
    return this;
  }

  /**
   * Variation weight.
   * @return weight
   */
  @javax.annotation.Nullable
  public String getWeight() {
    return weight;
  }

  public void setWeight(@javax.annotation.Nullable String weight) {
    this.weight = weight;
  }


  public ProductVariation dimensions(@javax.annotation.Nullable ProductDimension dimensions) {
    this.dimensions = dimensions;
    return this;
  }

  /**
   * Get dimensions
   * @return dimensions
   */
  @javax.annotation.Nullable
  public ProductDimension getDimensions() {
    return dimensions;
  }

  public void setDimensions(@javax.annotation.Nullable ProductDimension dimensions) {
    this.dimensions = dimensions;
  }


  public ProductVariation shippingClass(@javax.annotation.Nullable String shippingClass) {
    this.shippingClass = shippingClass;
    return this;
  }

  /**
   * Shipping class slug.
   * @return shippingClass
   */
  @javax.annotation.Nullable
  public String getShippingClass() {
    return shippingClass;
  }

  public void setShippingClass(@javax.annotation.Nullable String shippingClass) {
    this.shippingClass = shippingClass;
  }


  public ProductVariation shippingClassId(@javax.annotation.Nullable Integer shippingClassId) {
    this.shippingClassId = shippingClassId;
    return this;
  }

  /**
   * Shipping class ID.
   * @return shippingClassId
   */
  @javax.annotation.Nullable
  public Integer getShippingClassId() {
    return shippingClassId;
  }

  public void setShippingClassId(@javax.annotation.Nullable Integer shippingClassId) {
    this.shippingClassId = shippingClassId;
  }


  public ProductVariation image(@javax.annotation.Nullable ProductImage image) {
    this.image = image;
    return this;
  }

  /**
   * Get image
   * @return image
   */
  @javax.annotation.Nullable
  public ProductImage getImage() {
    return image;
  }

  public void setImage(@javax.annotation.Nullable ProductImage image) {
    this.image = image;
  }


  public ProductVariation attributes(@javax.annotation.Nullable List<ProductAttribute> attributes) {
    this.attributes = attributes;
    return this;
  }

  public ProductVariation addAttributesItem(ProductAttribute attributesItem) {
    if (this.attributes == null) {
      this.attributes = new ArrayList<>();
    }
    this.attributes.add(attributesItem);
    return this;
  }

  /**
   * List of attributes.
   * @return attributes
   */
  @javax.annotation.Nullable
  public List<ProductAttribute> getAttributes() {
    return attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<ProductAttribute> attributes) {
    this.attributes = attributes;
  }


  public ProductVariation menuOrder(@javax.annotation.Nullable Integer menuOrder) {
    this.menuOrder = menuOrder;
    return this;
  }

  /**
   * Menu order, used to custom sort products.
   * @return menuOrder
   */
  @javax.annotation.Nullable
  public Integer getMenuOrder() {
    return menuOrder;
  }

  public void setMenuOrder(@javax.annotation.Nullable Integer menuOrder) {
    this.menuOrder = menuOrder;
  }


  public ProductVariation metaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
    return this;
  }

  public ProductVariation addMetaDataItem(MetaData metaDataItem) {
    if (this.metaData == null) {
      this.metaData = new ArrayList<>();
    }
    this.metaData.add(metaDataItem);
    return this;
  }

  /**
   * Meta data properties.
   * @return metaData
   */
  @javax.annotation.Nullable
  public List<MetaData> getMetaData() {
    return metaData;
  }

  public void setMetaData(@javax.annotation.Nullable List<MetaData> metaData) {
    this.metaData = metaData;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductVariation productVariation = (ProductVariation) o;
    return Objects.equals(this.variationId, productVariation.variationId) &&
        Objects.equals(this.dateCreated, productVariation.dateCreated) &&
        Objects.equals(this.dateCreatedGmt, productVariation.dateCreatedGmt) &&
        Objects.equals(this.dateModified, productVariation.dateModified) &&
        Objects.equals(this.dateModifiedGmt, productVariation.dateModifiedGmt) &&
        Objects.equals(this.description, productVariation.description) &&
        Objects.equals(this.permalink, productVariation.permalink) &&
        Objects.equals(this.sku, productVariation.sku) &&
        Objects.equals(this.price, productVariation.price) &&
        Objects.equals(this.regularPrice, productVariation.regularPrice) &&
        Objects.equals(this.salePrice, productVariation.salePrice) &&
        Objects.equals(this.dateOnSaleFrom, productVariation.dateOnSaleFrom) &&
        Objects.equals(this.dateOnSaleFromGmt, productVariation.dateOnSaleFromGmt) &&
        Objects.equals(this.dateOnSaleTo, productVariation.dateOnSaleTo) &&
        Objects.equals(this.dateOnSaleToGmt, productVariation.dateOnSaleToGmt) &&
        Objects.equals(this.onSale, productVariation.onSale) &&
        Objects.equals(this.status, productVariation.status) &&
        Objects.equals(this.purchasable, productVariation.purchasable) &&
        Objects.equals(this.virtual, productVariation.virtual) &&
        Objects.equals(this.downloadable, productVariation.downloadable) &&
        Objects.equals(this.downloads, productVariation.downloads) &&
        Objects.equals(this.downloadLimit, productVariation.downloadLimit) &&
        Objects.equals(this.downloadExpiry, productVariation.downloadExpiry) &&
        Objects.equals(this.taxStatus, productVariation.taxStatus) &&
        Objects.equals(this.taxClass, productVariation.taxClass) &&
        Objects.equals(this.manageStock, productVariation.manageStock) &&
        Objects.equals(this.stockQuantity, productVariation.stockQuantity) &&
        Objects.equals(this.stockStatus, productVariation.stockStatus) &&
        Objects.equals(this.backorders, productVariation.backorders) &&
        Objects.equals(this.backordersAllowed, productVariation.backordersAllowed) &&
        Objects.equals(this.backordered, productVariation.backordered) &&
        Objects.equals(this.weight, productVariation.weight) &&
        Objects.equals(this.dimensions, productVariation.dimensions) &&
        Objects.equals(this.shippingClass, productVariation.shippingClass) &&
        Objects.equals(this.shippingClassId, productVariation.shippingClassId) &&
        Objects.equals(this.image, productVariation.image) &&
        Objects.equals(this.attributes, productVariation.attributes) &&
        Objects.equals(this.menuOrder, productVariation.menuOrder) &&
        Objects.equals(this.metaData, productVariation.metaData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(variationId, dateCreated, dateCreatedGmt, dateModified, dateModifiedGmt, description, permalink, sku, price, regularPrice, salePrice, dateOnSaleFrom, dateOnSaleFromGmt, dateOnSaleTo, dateOnSaleToGmt, onSale, status, purchasable, virtual, downloadable, downloads, downloadLimit, downloadExpiry, taxStatus, taxClass, manageStock, stockQuantity, stockStatus, backorders, backordersAllowed, backordered, weight, dimensions, shippingClass, shippingClassId, image, attributes, menuOrder, metaData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductVariation {\n");
    sb.append("    id: ").append(toIndentedString(variationId)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateCreatedGmt: ").append(toIndentedString(dateCreatedGmt)).append("\n");
    sb.append("    dateModified: ").append(toIndentedString(dateModified)).append("\n");
    sb.append("    dateModifiedGmt: ").append(toIndentedString(dateModifiedGmt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    permalink: ").append(toIndentedString(permalink)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    regularPrice: ").append(toIndentedString(regularPrice)).append("\n");
    sb.append("    salePrice: ").append(toIndentedString(salePrice)).append("\n");
    sb.append("    dateOnSaleFrom: ").append(toIndentedString(dateOnSaleFrom)).append("\n");
    sb.append("    dateOnSaleFromGmt: ").append(toIndentedString(dateOnSaleFromGmt)).append("\n");
    sb.append("    dateOnSaleTo: ").append(toIndentedString(dateOnSaleTo)).append("\n");
    sb.append("    dateOnSaleToGmt: ").append(toIndentedString(dateOnSaleToGmt)).append("\n");
    sb.append("    onSale: ").append(toIndentedString(onSale)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    purchasable: ").append(toIndentedString(purchasable)).append("\n");
    sb.append("    virtual: ").append(toIndentedString(virtual)).append("\n");
    sb.append("    downloadable: ").append(toIndentedString(downloadable)).append("\n");
    sb.append("    downloads: ").append(toIndentedString(downloads)).append("\n");
    sb.append("    downloadLimit: ").append(toIndentedString(downloadLimit)).append("\n");
    sb.append("    downloadExpiry: ").append(toIndentedString(downloadExpiry)).append("\n");
    sb.append("    taxStatus: ").append(toIndentedString(taxStatus)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    manageStock: ").append(toIndentedString(manageStock)).append("\n");
    sb.append("    stockQuantity: ").append(toIndentedString(stockQuantity)).append("\n");
    sb.append("    stockStatus: ").append(toIndentedString(stockStatus)).append("\n");
    sb.append("    backorders: ").append(toIndentedString(backorders)).append("\n");
    sb.append("    backordersAllowed: ").append(toIndentedString(backordersAllowed)).append("\n");
    sb.append("    backordered: ").append(toIndentedString(backordered)).append("\n");
    sb.append("    weight: ").append(toIndentedString(weight)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    shippingClass: ").append(toIndentedString(shippingClass)).append("\n");
    sb.append("    shippingClassId: ").append(toIndentedString(shippingClassId)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    menuOrder: ").append(toIndentedString(menuOrder)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert an instance of ProductVariation to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

