/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import java.util.Objects;

//import com.google.gson.annotations.SerializedName;

import org.jetbrains.annotations.Nullable;
import uk.co.twinn.api.woocommerce.core.JacksonObjectMapper;

/**
 * ProductDownload
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ProductDownload {
  public static final String SERIALIZED_NAME_ID = "id";
  //@SerializedName(SERIALIZED_NAME_ID)
  @Nullable
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  //@SerializedName(SERIALIZED_NAME_NAME)
  @Nullable
  private String name;

  public static final String SERIALIZED_NAME_FILE = "file";
  //@SerializedName(SERIALIZED_NAME_FILE)
  @Nullable
  private String _file;

  public ProductDownload() {
  }

  public ProductDownload id(@Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * File ID.
   * @return id
   */
  @Nullable
  public String getId() {
    return id;
  }

  public void setId(@Nullable String id) {
    this.id = id;
  }


  public ProductDownload name(@Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * File name.
   * @return name
   */
  @Nullable
  public String getName() {
    return name;
  }

  public void setName(@Nullable String name) {
    this.name = name;
  }


  public ProductDownload _file(@Nullable String _file) {
    this._file = _file;
    return this;
  }

  /**
   * File URL.
   * @return _file
   */
  @Nullable
  public String getFile() {
    return _file;
  }

  public void setFile(@Nullable String _file) {
    this._file = _file;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductDownload productDownload = (ProductDownload) o;
    return Objects.equals(this.id, productDownload.id) &&
        Objects.equals(this.name, productDownload.name) &&
        Objects.equals(this._file, productDownload._file);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, _file);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductDownload {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  /**
   * Convert an instance of ProductDownload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
      return new JacksonObjectMapper().toJson(this);
  }
}

