/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import com.google.gson.annotations.SerializedName;

import java.time.LocalDateTime;

/**
 * ProductReview
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ProductReview {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_DATE_CREATED = "date_created";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED)
  @javax.annotation.Nullable
  private LocalDateTime dateCreated;

  public static final String SERIALIZED_NAME_DATE_CREATED_GMT = "date_created_gmt";
  @SerializedName(SERIALIZED_NAME_DATE_CREATED_GMT)
  @javax.annotation.Nullable
  private LocalDateTime dateCreatedGmt;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nullable
  private Integer productId;

  /**
   * Status of the review.
   */
  public enum StatusEnum {
    APPROVED("approved"),

    HOLD("hold"),

    SPAM("spam"),

    UNSPAM("unspam"),

    TRASH("trash"),

    UNTRASH("untrash");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }


  }

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private StatusEnum status = StatusEnum.APPROVED;

  public static final String SERIALIZED_NAME_REVIEWER = "reviewer";
  @SerializedName(SERIALIZED_NAME_REVIEWER)
  @javax.annotation.Nullable
  private String reviewer;

  public static final String SERIALIZED_NAME_REVIEWER_EMAIL = "reviewer_email";
  @SerializedName(SERIALIZED_NAME_REVIEWER_EMAIL)
  @javax.annotation.Nullable
  private String reviewerEmail;

  public static final String SERIALIZED_NAME_REVIEW = "review";
  @SerializedName(SERIALIZED_NAME_REVIEW)
  @javax.annotation.Nullable
  private String review;

  public static final String SERIALIZED_NAME_RATING = "rating";
  @SerializedName(SERIALIZED_NAME_RATING)
  @javax.annotation.Nullable
  private Integer rating;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  @javax.annotation.Nullable
  private Boolean verified;

  public ProductReview() {
  }

  public ProductReview(
     Integer id,
     LocalDateTime dateCreated,
     LocalDateTime dateCreatedGmt
  ) {
    this();
    this.id = id;
    this.dateCreated = dateCreated;
    this.dateCreatedGmt = dateCreatedGmt;
  }

  /**
   * Unique identifier for the resource.
   * @return id
   */
  @javax.annotation.Nullable
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
        this.id = id;
    }

  /**
   * The date the review was created, in the site&#39;s timezone.
   * @return dateCreated
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateCreated() {
    return dateCreated;
  }



  /**
   * The date the review was created, as GMT.
   * @return dateCreatedGmt
   */
  @javax.annotation.Nullable
  public LocalDateTime getDateCreatedGmt() {
    return dateCreatedGmt;
  }



  public ProductReview productId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Unique identifier for the product that the review belongs to.
   * @return productId
   */
  @javax.annotation.Nullable
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
  }


  public ProductReview status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Status of the review.
   * @return status
   */
  @JsonIgnore
  @javax.annotation.Nullable
  public StatusEnum getStatus() {
    return status;
  }

  @JsonProperty("status")
  public String getStatusAsString() {
      return status != null ? status.getValue() : "";
  }

  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }
  @JsonProperty("status")
  public void setStatusAsString(@javax.annotation.Nullable String status) {

      if (status != null){this.status.fromValue(status);}

  }


  public ProductReview reviewer(@javax.annotation.Nullable String reviewer) {
    this.reviewer = reviewer;
    return this;
  }

  /**
   * Reviewer name.
   * @return reviewer
   */
  @javax.annotation.Nullable
  public String getReviewer() {
    return reviewer;
  }

  public void setReviewer(@javax.annotation.Nullable String reviewer) {
    this.reviewer = reviewer;
  }


  public ProductReview reviewerEmail(@javax.annotation.Nullable String reviewerEmail) {
    this.reviewerEmail = reviewerEmail;
    return this;
  }

  /**
   * Reviewer email.
   * @return reviewerEmail
   */
  @javax.annotation.Nullable
  public String getReviewerEmail() {
    return reviewerEmail;
  }

  public void setReviewerEmail(@javax.annotation.Nullable String reviewerEmail) {
    this.reviewerEmail = reviewerEmail;
  }


  public ProductReview review(@javax.annotation.Nullable String review) {
    this.review = review;
    return this;
  }

  /**
   * The content of the review.
   * @return review
   */
  @javax.annotation.Nullable
  public String getReview() {
    return review;
  }

  public void setReview(@javax.annotation.Nullable String review) {
    this.review = review;
  }


  public ProductReview rating(@javax.annotation.Nullable Integer rating) {
    this.rating = rating;
    return this;
  }

  /**
   * Review rating (0 to 5).
   * minimum: 0
   * maximum: 5
   * @return rating
   */
  @javax.annotation.Nullable
  public Integer getRating() {
    return rating;
  }

  public void setRating(@javax.annotation.Nullable Integer rating) {
    this.rating = rating;
  }


  public ProductReview verified(@javax.annotation.Nullable Boolean verified) {
    this.verified = verified;
    return this;
  }

  /**
   * Shows if the reviewer bought the product or not.
   * @return verified
   */
  @javax.annotation.Nullable
  public Boolean getVerified() {
    return verified;
  }

  public void setVerified(@javax.annotation.Nullable Boolean verified) {
    this.verified = verified;
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductReview {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dateCreated: ").append(toIndentedString(dateCreated)).append("\n");
    sb.append("    dateCreatedGmt: ").append(toIndentedString(dateCreatedGmt)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    reviewer: ").append(toIndentedString(reviewer)).append("\n");
    sb.append("    reviewerEmail: ").append(toIndentedString(reviewerEmail)).append("\n");
    sb.append("    review: ").append(toIndentedString(review)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

