/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import java.util.Objects;

import javax.annotation.Nullable;
import uk.co.twinn.api.woocommerce.core.JacksonObjectMapper;

/**
 * ProductAttributeTerm
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ProductAttributeTerm {
  public static final String SERIALIZED_NAME_ID = "id";
  //@SerializedName(SERIALIZED_NAME_ID)
  @Nullable
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  //@SerializedName(SERIALIZED_NAME_NAME)
  @Nullable
  private String name;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  //@SerializedName(SERIALIZED_NAME_SLUG)
  @Nullable
  private String slug;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  //@SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @Nullable
  private String description;

  public static final String SERIALIZED_NAME_MENU_ORDER = "menu_order";
  //@SerializedName(SERIALIZED_NAME_MENU_ORDER)
  @Nullable
  private Integer menuOrder;

  public static final String SERIALIZED_NAME_COUNT = "count";
  //@SerializedName(SERIALIZED_NAME_COUNT)
  @Nullable
  private Integer count;

  public ProductAttributeTerm() {
  }

  public ProductAttributeTerm id(@Nullable Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Term ID.
   * @return id
   */
  @Nullable
  public Integer getId() {
    return id;
  }

  public void setId(@Nullable Integer id) {
    this.id = id;
  }


  public ProductAttributeTerm name(@Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Term name.
   * @return name
   */
  @Nullable
  public String getName() {
    return name;
  }

  public void setName(@Nullable String name) {
    this.name = name;
  }


  public ProductAttributeTerm slug(@Nullable String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Term slug.
   * @return slug
   */
  @Nullable
  public String getSlug() {
    return slug;
  }

  public void setSlug(@Nullable String slug) {
    this.slug = slug;
  }


  public ProductAttributeTerm description(@Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Term description.
   * @return description
   */
  @Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@Nullable String description) {
    this.description = description;
  }


  public ProductAttributeTerm menuOrder(@Nullable Integer menuOrder) {
    this.menuOrder = menuOrder;
    return this;
  }

  /**
   * Menu order.
   * @return menuOrder
   */
  @Nullable
  public Integer getMenuOrder() {
    return menuOrder;
  }

  public void setMenuOrder(@Nullable Integer menuOrder) {
    this.menuOrder = menuOrder;
  }


  public ProductAttributeTerm count(@Nullable Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Number of products in term.
   * @return count
   */
  @Nullable
  public Integer getCount() {
    return count;
  }

  public void setCount(@Nullable Integer count) {
    this.count = count;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductAttributeTerm productAttributeTerm = (ProductAttributeTerm) o;
    return Objects.equals(this.id, productAttributeTerm.id) &&
        Objects.equals(this.name, productAttributeTerm.name) &&
        Objects.equals(this.slug, productAttributeTerm.slug) &&
        Objects.equals(this.description, productAttributeTerm.description) &&
        Objects.equals(this.menuOrder, productAttributeTerm.menuOrder) &&
        Objects.equals(this.count, productAttributeTerm.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, slug, description, menuOrder, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductAttributeTerm {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    menuOrder: ").append(toIndentedString(menuOrder)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert an instance of ProductAttributeTerm to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
      return new JacksonObjectMapper().toJson(this);
  }

}

