/*
 * Copyright (c) 2025.
 *
 * Crud+ ActionBuilder
 * Author: Chris Twinn
 * Licence: MIT Licence see LICENCE file
 * All Rights Reserved
 */

/*
 * WooCommerce REST API
 * The REST API is a powerful part of WooCommerce which lets you read and write various parts of WooCommerce data such as orders, products, coupons, customers, and shipping zones.
 *
 * The version of the OpenAPI document: v3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package uk.co.twinn.pl_wtx_woocommerce.model;

import java.util.Objects;

//import com.google.gson.annotations.SerializedName;

import org.jetbrains.annotations.Nullable;
import uk.co.twinn.api.woocommerce.core.JacksonObjectMapper;

/**
 * ReportSalesSummaryItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class ReportSalesSummaryItem {
  public static final String SERIALIZED_NAME_SALES = "sales";
  //@SerializedName(SERIALIZED_NAME_SALES)
  @Nullable
  private String sales;

  public static final String SERIALIZED_NAME_ORDERS = "orders";
  //@SerializedName(SERIALIZED_NAME_ORDERS)
  @Nullable
  private Integer orders;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  //@SerializedName(SERIALIZED_NAME_ITEMS)
  @Nullable
  private Integer items;

  public static final String SERIALIZED_NAME_TAX = "tax";
  //@SerializedName(SERIALIZED_NAME_TAX)
  @Nullable
  private String tax;

  public static final String SERIALIZED_NAME_SHIPPING = "shipping";
  //@SerializedName(SERIALIZED_NAME_SHIPPING)
  @Nullable
  private String shipping;

  public static final String SERIALIZED_NAME_DISCOUNT = "discount";
  //@SerializedName(SERIALIZED_NAME_DISCOUNT)
  @Nullable
  private String discount;

  public static final String SERIALIZED_NAME_CUSTOMERS = "customers";
  //@SerializedName(SERIALIZED_NAME_CUSTOMERS)
  @Nullable
  private Integer customers;

  public ReportSalesSummaryItem() {
  }

  public ReportSalesSummaryItem sales(@Nullable String sales) {
    this.sales = sales;
    return this;
  }

  /**
   * Get sales
   * @return sales
   */
  @Nullable
  public String getSales() {
    return sales;
  }

  public void setSales(@Nullable String sales) {
    this.sales = sales;
  }


  public ReportSalesSummaryItem orders(@Nullable Integer orders) {
    this.orders = orders;
    return this;
  }

  /**
   * Get orders
   * @return orders
   */
  @Nullable
  public Integer getOrders() {
    return orders;
  }

  public void setOrders(@Nullable Integer orders) {
    this.orders = orders;
  }


  public ReportSalesSummaryItem items(@Nullable Integer items) {
    this.items = items;
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @Nullable
  public Integer getItems() {
    return items;
  }

  public void setItems(@Nullable Integer items) {
    this.items = items;
  }


  public ReportSalesSummaryItem tax(@Nullable String tax) {
    this.tax = tax;
    return this;
  }

  /**
   * Get tax
   * @return tax
   */
  @Nullable
  public String getTax() {
    return tax;
  }

  public void setTax(@Nullable String tax) {
    this.tax = tax;
  }


  public ReportSalesSummaryItem shipping(@Nullable String shipping) {
    this.shipping = shipping;
    return this;
  }

  /**
   * Get shipping
   * @return shipping
   */
  @Nullable
  public String getShipping() {
    return shipping;
  }

  public void setShipping(@Nullable String shipping) {
    this.shipping = shipping;
  }


  public ReportSalesSummaryItem discount(@Nullable String discount) {
    this.discount = discount;
    return this;
  }

  /**
   * Get discount
   * @return discount
   */
  @Nullable
  public String getDiscount() {
    return discount;
  }

  public void setDiscount(@Nullable String discount) {
    this.discount = discount;
  }


  public ReportSalesSummaryItem customers(@Nullable Integer customers) {
    this.customers = customers;
    return this;
  }

  /**
   * Get customers
   * @return customers
   */
  @Nullable
  public Integer getCustomers() {
    return customers;
  }

  public void setCustomers(@Nullable Integer customers) {
    this.customers = customers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportSalesSummaryItem reportSalesSummaryItem = (ReportSalesSummaryItem) o;
    return Objects.equals(this.sales, reportSalesSummaryItem.sales) &&
        Objects.equals(this.orders, reportSalesSummaryItem.orders) &&
        Objects.equals(this.items, reportSalesSummaryItem.items) &&
        Objects.equals(this.tax, reportSalesSummaryItem.tax) &&
        Objects.equals(this.shipping, reportSalesSummaryItem.shipping) &&
        Objects.equals(this.discount, reportSalesSummaryItem.discount) &&
        Objects.equals(this.customers, reportSalesSummaryItem.customers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sales, orders, items, tax, shipping, discount, customers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportSalesSummaryItem {\n");
    sb.append("    sales: ").append(toIndentedString(sales)).append("\n");
    sb.append("    orders: ").append(toIndentedString(orders)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("    shipping: ").append(toIndentedString(shipping)).append("\n");
    sb.append("    discount: ").append(toIndentedString(discount)).append("\n");
    sb.append("    customers: ").append(toIndentedString(customers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert an instance of ReportSalesSummaryItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
      return new JacksonObjectMapper().toJson(this);
  }
}

